---
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Kubernetes Master
  hosts: master
  become: yes
  roles:
    - kubernetes

- name: Setup Kubernetes Workers
  hosts: workers
  become: yes
  roles:
    - kubernetes

- name: Deploy ELK Stack on Master
  hosts: master
  become: yes
  roles:
    - elk
