---
- name: Установка базовых утилит на серверы     # Название playbook
  hosts: all                                    # Применяется ко всем хостам из инвентаря
  become: yes                                   # Выполнять команды с правами root (sudo)

  tasks:                                       # Список задач
    - name: Установка пакетов                  # Название задачи
      ansible.builtin.package:                 # Используем модуль package (работает с разными пакетными менеджерами)
        name:                                  # Список пакетов для установки
          - zsh
          - htop
          - mc
          - ncdu
        state: present                       # Указываем, что пакеты должны быть установлены
      register: package_install              # Сохраняем результат выполнения в переменную

    - name: Проверка успешности установки     # Задача для отладки
      ansible.builtin.debug:
        msg: "Пакеты успешно установлены"
      when: package_install.changed          # Выводим сообщение только если были изменения